hi


*italics*
# heading #
## sub heading ##
[python website](https://www.python.org)

#numpy

In [3]:
import numpy as np

In [4]:
my_list=[1,2,3,4,5]

In [5]:
np.array(my_list) #create an array

array([1, 2, 3, 4, 5])

In [6]:
np.array([12,23,34,45,56])  #one dimensional array

array([12, 23, 34, 45, 56])

In [ ]:
my_list=[[1,2,3],[4,5,6],[7,8,9]] 
print(my_list)
arr=np.array(my_list)
print(arr)       #two dimensional array

In [13]:
my_list_2=[[[100,101,102],[103,104,105]],[[201,202,203],[204,205,206]]]
arr1=np.array(my_list_2) #3 dimensional array
print(arr1)

[[[100 101 102]
  [103 104 105]]

 [[201 202 203]
  [204 205 206]]]


In [14]:
np.zeros(4)

array([0., 0., 0., 0.])

In [22]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [3]:
#Day 2

import numpy as np
arr_a=np.arange(10)

In [4]:
arr_a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# arange #
arr_b=np.arange(10,25,5)
print(arr_b)

[10 15 20]


In [8]:
# linspace #
arr_c=np.linspace(1,100,10)
print(arr_c)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [9]:
arr_d=np.linspace(0,1,5)
print(arr_d)

[0.   0.25 0.5  0.75 1.  ]


In [11]:
#eye for identity matrix
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
b=np.eye(5)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
#indexing
my_list=[[1,2,3],[4,5,6],[7,8,9]] 
print(my_list)           #2d array
arr=np.array(my_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [17]:
arr[1][2]

6

In [18]:
arr[1,2]

6

In [19]:
my_list_2=[[[100,101,102],[103,104,105]],[[201,202,203],[204,205,206]]]
arr1=np.array(my_list_2) #3 dimensional array
print(arr1)

[[[100 101 102]
  [103 104 105]]

 [[201 202 203]
  [204 205 206]]]


In [22]:
arr1[1,0,1]

202

In [23]:
arr1[0,0,2]

102

In [24]:
arr1[0,1,1]

104

In [25]:
 #[[[100 101 102]    0,0,[0,1,2]
 # [103 104 105]]    0,1,[0,1,2]

 #[[201 202 203]     1,0,[0,1,2]
 # [204 205 206]]]   1,1,[0,1,2]

In [26]:
#Slicing
#for 2d array
arr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr[:2] #no need to mention the zero

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
#slicing for 3d array
arr[:2,1:]  

array([[2, 3],
       [5, 6]])

In [32]:
arr1[1:,:,1:]

array([[[202, 203],
        [205, 206]]])

In [33]:
#Attributes
#1.size

In [34]:
arr.size #it will give number of element in array

9

In [35]:
arr1.size

12

In [38]:
#2.Shape
arr.shape #2d

(3, 3)

In [39]:
arr1.shape #3d

(2, 2, 3)

In [40]:
#3.dtype
arr.dtype #integer 32, float 64

dtype('int32')

In [42]:
fruits=np.array(["apple","mango","cherry"])
fruits.dtype #here it will give less than the largest element,here cherry has 6,which is highest

dtype('<U6')

In [43]:
fruits=np.array(["apple","mango","cherry","watermelon"])
fruits.dtype #gives less than 10 since watermelon has highest of 10 letters

dtype('<U10')

In [46]:
bool_arr=np.array([True,False,True])
bool_arr.dtype

dtype('bool')

In [49]:
complex_arr=np.array([(1+2j),(2+2j)])
complex_arr.dtype

dtype('complex128')

In [51]:
#convert integer datatype to float
np.ones((3,3)) #here it default gives 1.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
#so to change that 1. to 1
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [54]:
arr13=np.ones((3,3),dtype=int) #this will be a integer which take 32 bit
arr13.dtype

dtype('int32')

In [55]:
#so to change 32 bit to 8 bit
arr13=np.ones((3,3),dtype="i1") 
arr13.dtype  #herei i1 because 1byte=8bits

dtype('int8')

In [56]:
arr13=np.ones((3,3),dtype="i2") 
arr13.dtype #i2=16 bits

dtype('int16')