In [1]:
import numpy as np

In [5]:
mat1=np.eye(3,dtype=int)
mat1 #identity matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [8]:
mat2=np.eye(3,4,dtype=int) #4 will give a 4th column in identity matrix
mat2

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [12]:
c=np.eye(3,4,k=1)# k=positive value gives shift to upper matrix(upper values than diagonal)
c

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
c=np.eye(3,4,k=-1)# k=positive value gives shift to lower matrix(lower values than diagonal)
c

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [14]:
c=np.eye(3,4,k=2)# k=positive value gives shift of 2 in diagonal to upper matrix(upper values than diagonal)
c

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [17]:
A=np.array([[2,3,4],[5,6,7],[8,9,10]])
print(A)
np.diag(A,k=1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


array([3, 7])

In [18]:
#lower triangular matrix
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [19]:
np.tri(4,5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.]])

In [20]:
#upper triangular matrix
np.triu(A)

array([[ 2,  3,  4],
       [ 0,  6,  7],
       [ 0,  0, 10]])

In [23]:
#vandermonde matrix #power of rows will be column
np.vander([1,2,3])

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

In [27]:
np.vander([1,2,3],6)  #6 will be number of column

array([[  1,   1,   1,   1,   1,   1],
       [ 32,  16,   8,   4,   2,   1],
       [243,  81,  27,   9,   3,   1]])

In [28]:
np.vander([1,2,3],6,increasing=True)

array([[  1,   1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16,  32],
       [  1,   3,   9,  27,  81, 243]])

In [44]:
np.random.rand(5,3) 

array([[8.90125431e-01, 1.33962601e-01, 5.70500388e-01],
       [5.17929468e-01, 9.94746152e-01, 7.37975765e-01],
       [7.40234415e-01, 8.20697205e-01, 1.85813739e-01],
       [8.24573021e-01, 9.85536058e-04, 1.22025646e-01],
       [4.27348088e-01, 9.18140009e-01, 6.80875680e-01]])

In [43]:
np.random.randn(4,3) #mean=0,S.D=1 Normal distribution

array([[-0.07847375, -0.74412555, -0.54121803],
       [ 0.53888577,  1.98263472, -0.09771127],
       [ 0.19585657,  1.94133723,  0.91990163],
       [-0.74877851,  0.44064824, -0.14345669]])

In [52]:
np.random.randint(2,10,5) #2,10 is range, 5 is the number of elements

array([6, 8, 5, 6, 2])

In [54]:
np.random.randint(2,10,(5,4)) #size of array in tuples

array([[3, 8, 2, 5],
       [3, 2, 2, 4],
       [5, 8, 3, 6],
       [6, 9, 3, 9],
       [3, 7, 5, 4]])

In [61]:
#reshape
arr=np.arange(1,10) #create last-1 elements
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
#copy array and view array
slice_arr=arr[1:,2:]
slice_arr

array([[ 7,  8],
       [11, 12]])

In [68]:
slice_arr[0,1]=100
slice_arr

array([[  7, 100],
       [ 11,  12]])

In [70]:
copy_arr=arr.copy()
copy_arr

array([[  1,   2,   3,   4],
       [  5,   6,   7, 100],
       [  9,  10,  11,  12]])

In [72]:
copy_arr[1,3]=7
copy_arr #no change in parent array happens

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  7],
       [ 9, 10, 11, 12]])

In [2]:
arr

NameError: name 'arr' is not defined

In [74]:
#view will make a change in parent array also

In [78]:
copy_arr.base 

In [79]:
view_arr=arr.view()

In [81]:
view_arr.base #it will give the parent array of view_arr

array([  1,   2,   3,   4,   5,   6,   7, 100,   9,  10,  11,  12])