In [2]:
import numpy as np

In [3]:
#flattening of array
arr=np.arange(1,33)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [48]:
ar=arr.reshape(2,-1,4)
ar

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]])

In [13]:
ar.reshape(-1) #flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [8]:
ar.shape

(2, 4, 4)

In [9]:
np.ravel(ar)  #ravel - flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [14]:
arr1=np.arange(1,17).reshape(2,2,4)
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [16]:
for i in arr1:
    for j in i:
        for k in j:
            print(k,end=' ')  # to get all element in array 

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

In [17]:
for z in np.nditer(arr1):
    print(z,end=" ")   #another method for iterating value inside array

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

In [38]:
for s in np.nditer(arr1,flags=["buffered"],op_dtypes="S"):
    print(s,end="  ")

b'1'  b'2'  b'3'  b'4'  b'5'  b'6'  b'7'  b'8'  b'9'  b'10'  b'11'  b'12'  b'13'  b'14'  b'15'  b'16'  

In [40]:
#enumerate #automatically give index
list=[12,23,34,45]
for idx,item in enumerate(list):
    print(idx," ",item)

0   12
1   23
2   34
3   45


In [42]:
for idx,item in np.ndenumerate(arr1):
    print(idx,"-",item)  #iterating through index

(0, 0, 0) - 1
(0, 0, 1) - 2
(0, 0, 2) - 3
(0, 0, 3) - 4
(0, 1, 0) - 5
(0, 1, 1) - 6
(0, 1, 2) - 7
(0, 1, 3) - 8
(1, 0, 0) - 9
(1, 0, 1) - 10
(1, 0, 2) - 11
(1, 0, 3) - 12
(1, 1, 0) - 13
(1, 1, 1) - 14
(1, 1, 2) - 15
(1, 1, 3) - 16


In [52]:
#Full
np.full((3,4),fill_value=100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [53]:
#Joining 2 arrays together

In [60]:
a1=np.array([1,2,3])
a2=np.array([5,8,9])
np.concatenate((a1,a2))

array([1, 2, 3, 5, 8, 9])

In [61]:
a1=np.arange(3)
a2=np.arange(5,8)
np.concatenate((a1,a2))

array([0, 1, 2, 5, 6, 7])

In [3]:
ar_2d=np.arange(12).reshape((3,4))   #joining 2 arrays in 2D
ar_2d1=np.ones((3,4))

In [7]:
ar_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
ar_2d1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
res=np.concatenate((ar_2d,ar_2d1))
res

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [16]:
ar_3d=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
ar_3d1=np.array([[[21,22,23],[24,25,26],[27,28,29],[30,31,32]]])
print(ar_3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [17]:
print(ar_3d1)

[[[21 22 23]
  [24 25 26]
  [27 28 29]
  [30 31 32]]]


In [14]:
np.concatenate((ar_3d,ar_3d1))  #joining 2 array in 3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32]]])

In [19]:
np.concatenate((ar_3d,ar_3d1),axis=2)

array([[[ 1,  2,  3, 21, 22, 23],
        [ 4,  5,  6, 24, 25, 26],
        [ 7,  8,  9, 27, 28, 29],
        [10, 11, 12, 30, 31, 32]]])

In [20]:
#in 3d axis=0 is the first 2d row,axis=1 is 2nd 2d row,axis=2 is 3rd row

In [21]:
np.concatenate((ar_3d,ar_3d1),axis=1)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32]]])

In [22]:
#stacking

In [23]:
A=np.array([1,2,3])
B=np.array([4,5,6])

In [24]:
np.stack((A,B))

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.hstack((A,B)) #hstack keep second array in right side of first array

array([1, 2, 3, 4, 5, 6])

In [26]:
np.vstack((A,B)) ##vstack keep second array down of first array

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.stack((A,B),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#stacking in 2D

In [32]:
stack_2d=np.arange(12).reshape((3,4)) 
stack_2d1=np.ones((3,4))

In [33]:
stack_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
stack_2d1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.stack((stack_2d,stack_2d1))

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [36]:
np.stack((stack_2d,stack_2d1),axis=1) #it will add row after second array row

array([[[ 0.,  1.,  2.,  3.],
        [ 1.,  1.,  1.,  1.]],

       [[ 4.,  5.,  6.,  7.],
        [ 1.,  1.,  1.,  1.]],

       [[ 8.,  9., 10., 11.],
        [ 1.,  1.,  1.,  1.]]])

In [37]:
np.stack((stack_2d,stack_2d1),axis=2) #it will alternatively become first row element and second row element

array([[[ 0.,  1.],
        [ 1.,  1.],
        [ 2.,  1.],
        [ 3.,  1.]],

       [[ 4.,  1.],
        [ 5.,  1.],
        [ 6.,  1.],
        [ 7.,  1.]],

       [[ 8.,  1.],
        [ 9.,  1.],
        [10.,  1.],
        [11.,  1.]]])

In [ ]:
#dstack for 3D arrys is also there