In [2]:
#Split
import numpy as np

In [11]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
np.split(arr,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [10]:
np.split(arr,[2,3,5]) #split in 0,1 then 2 then 3,4 then rest

[array([0, 1]), array([2]), array([3, 4]), array([ 5,  6,  7,  8,  9, 10, 11])]

In [ ]:
 #Array split

In [12]:
arr1=np.arange(12).reshape((4,3))

In [14]:
np.array_split(arr1,5) #l%N of (l/N)+1

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]]),
 array([], shape=(0, 3), dtype=int32)]

In [15]:
#hsplit

In [18]:
np.hsplit(arr1,3) #splitting columnwise to 3 parts

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [19]:
np.vsplit(arr1,4) #splitting rowwise into 4

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]])]

In [21]:
np.vsplit(arr1,2)  #it will be split horizontally to 2 sections

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [22]:
#dsplit is also possible

In [ ]:
#Append

In [23]:
np.append(arr,[12,13])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [24]:
np.insert(arr,1,[100,200])

array([  0, 100, 200,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
        11])

In [28]:
#Masking (Array with boolean value)

In [29]:
q=np.array([12,2,34,45,56])
q

array([12,  2, 34, 45, 56])

In [31]:
mask=np.array([True,False,False,False,True])
mask

array([ True, False, False, False,  True])

In [32]:
q[mask]

array([12, 56])

In [33]:
q>30  #used in conditional arrays also

array([False, False,  True,  True,  True])

In [34]:
q[q>30]

array([34, 45, 56])

In [35]:
q[q%2==0]

array([12,  2, 34, 56])

In [37]:
#Trimming Zeros
#if tailing and initial arrays are zero,then you can remove it using this

In [38]:
tz=np.array([0,0,0,12,23,34,0,56,0,0])

In [39]:
np.trim_zeros(tz)

array([12, 23, 34,  0, 56])

In [40]:
np.trim_zeros(tz,trim="f") #trim zero from first

array([12, 23, 34,  0, 56,  0,  0])

In [41]:
np.trim_zeros(tz,trim="b") #trim zero from last

array([ 0,  0,  0, 12, 23, 34,  0, 56])

In [42]:
#Flipping

In [44]:
v=np.arange(1,13).reshape(3,4)
v

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
np.flip(v) #elements will be reversed

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [47]:
np.flip(v,axis=1) #element is reversed in each row

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [48]:
np.fliplr(v) 
#using instead of np.flip(v,axis=1)
#flippinf from left to right

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [49]:
np.flipud(v) #flipping from up to down

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [50]:
#if we use it in 3D, then 2nd array comes over 1st

In [71]:
#Searching 
# Argmax and argmin ,nanargmax and nanargmin

In [54]:
np.argmax(arr1) #it will give the index of maximuum item in an array

11

In [55]:
np.argmin(arr1) #it will give the index of minimum item in an array

0

In [56]:
np.argmax(arr1,axis=1) #it will give index of maximum item in each row

array([2, 2, 2, 2], dtype=int64)

In [57]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [59]:
np.argmin(arr1,axis=1) #it will give index of minimum item in each row

array([0, 0, 0, 0], dtype=int64)

In [63]:
np.array([4,2,1,7,4,6,8,5,3,1,3,5]).reshape(4,3)

array([[4, 2, 1],
       [7, 4, 6],
       [8, 5, 3],
       [1, 3, 5]])

In [69]:
e=np.array([[12,23,np.nan],[40,20,20],[8,4,1]])
e

array([[12., 23., nan],
       [40., 20., 20.],
       [ 8.,  4.,  1.]])

In [70]:
np.nanargmax(e,axis=1)

array([1, 0, 0], dtype=int64)

In [72]:
np.nanargmin(e,axis=1)

array([0, 1, 2], dtype=int64)