In [1]:
import numpy as np

In [32]:
A=np.array([[3,2,1,4],[5,2,1,6]])
B=np.array([[3,2,1,4],[5,2,0,6]])
C=np.array([[True,False,False],[True,True,True]])
D=np.array([[0.1,0.0]])

In [12]:
for name,array in zip(list("ABC"),[A,B,C]):
    print(f"{name} :{np.all(array,axis=1)}")  

A :[ True  True]
B :[ True False]
C :[False  True]


In [13]:
#to check if any element in following array return logical value true 
for name,array in zip(list("ABCD"),[A,B,C,D]):
    print(f"{name} :{np.any(array,axis=0)}")

A :[ True  True  True  True]
B :[ True  True  True  True]
C :[ True  True  True]
D :True


In [15]:
#check if the following array has missing data

In [29]:
A=np.array([[3,2,1,np.nan],[5,np.nan,1,6]])
print(np.isnan(A))

[[False False False  True]
 [False  True False False]]


In [34]:
np.where(A==1) #it will find index of 1 in A

(array([0, 1], dtype=int64), array([2, 2], dtype=int64))

In [35]:
#check if following arrays are equal

In [36]:
A=np.array([0.4,0.5,0.3,0.9])
B=np.array([0.38,0.51,0.3,0.91])
print(A==B)

[False False  True False]


In [37]:
print(A>B)

[ True False False False]


In [38]:
print(np.greater(A,B))

[ True False False False]


In [39]:
#Create a 4x4 array of zeros

In [42]:
print(np.zeros((4,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [43]:
#create 10x10 matrix filled with 255

In [45]:
X=np.ones((10,10)) * 255
X

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])

In [48]:
Y=np.full((10,10),fill_value=255)
Y

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

In [50]:
#using numpy create onee dimensional array of all 2 digit numbers 
A=np.arange(100).reshape(10,10)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
# print following:
A=np.arange(10,100).reshape(9,-1)
A

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [54]:
#print 6x6 identity matrix

In [58]:
np.eye(6,dtype="int")

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [59]:
np.identity(6,dtype="int")

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [60]:
#set random seed to 10,then using numpy create a one dimensional array cosisting of 30 pseudo randomly geerated

In [62]:
np.random.seed(10)
print(np.random.rand(30))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]


In [63]:
np.random.seed(10)
print(np.random.randn(30))

[ 1.3315865   0.71527897 -1.54540029 -0.00838385  0.62133597 -0.72008556
  0.26551159  0.10854853  0.00429143 -0.17460021  0.43302619  1.20303737
 -0.96506567  1.02827408  0.22863013  0.44513761 -1.13660221  0.13513688
  1.484537   -1.07980489 -1.97772828 -1.7433723   0.26607016  2.38496733
  1.12369125  1.67262221  0.09914922  1.39799638 -0.27124799  0.61320418]


In [64]:
#normal distribution of N(100,5).seed to 30

In [67]:
np.random.seed(30)
sd=np.sqrt(5)
mu=100
print(sd * np.random.rand(10,4)+100)

[[101.44034873 100.85137951 101.48262019 100.36593415]
 [102.15245651 100.77515944 102.21762264 100.52560543]
 [101.3096522  100.90938671 100.3046292  101.21672573]
 [101.15867754 101.71474015 102.0881524  100.20058286]
 [100.43775784 102.22308466 100.52587958 100.53438977]
 [101.40670999 101.64340392 101.53918483 100.06961047]
 [102.0180823  100.64048886 101.24238746 100.84170125]
 [100.05953389 101.10495103 101.86647969 100.82060862]
 [101.15242944 101.05627184 100.86346232 101.66394093]
 [100.74962408 101.33144049 100.70689573 100.77423949]]


In [72]:
#iterate through each item
A=np.array([[1,4,3],[5,2,6]])

In [73]:
for  i in np.nditer(A):
    print(i)

1
4
3
5
2
6


In [74]:
#using numpy vreate a 1d array of equally distributed number of interval [0,1]
print(np.linspace(0,1,11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [75]:
#using numpy create a 1D contain possible result from big lotto game(random seed to 42)

In [79]:
np.random.seed(42)
Z=np.random.choice(range(1,50),size=6)
print(Z)

[39 29 15 43  8 21]


In [80]:
#create an identity matrix and change diagonal to 1-5.

In [84]:
K=np.arange(1,6)
np.diag(K)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [2]:
#using numpy create the following array.save this array to a binary file 'array.npy' and then load back that file to another variable.print this variable to the console.
#[[ 0 1 2 3]
#[ 4 5 6 7]
#[ 8 9 10 11]]

#use save() and load() methods

In [17]:
A=np.arange(12).reshape(3,-1)
np.savetxt("array.py",A)
B=np.loadtxt("array.py")
print(B)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [12]:
#using numpy create the following array.save this array to a text file 'array.txt' with two decimal point precision and then load back that file to another variable.print this variable to the console.
#[[ 0 1 2 3]
#[ 4 5 6 7]
#[ 8 9 10 11]]

#use savetxt() and loadtxt() methods

In [10]:
A=np.arange(12).reshape(3,4)
np.savetxt("array.txt",A,fmt="%0.2f")
B=np.loadtxt("array.txt")
print(B)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [18]:
#using numpy create the following array and convert to a list
#[[0, 1, 2, 3],
#[4, 5, 6, 7],
#[8, 9, 10, 11]]

#use tolist() method

In [19]:
A=np.arange(12).reshape(3,4)
print(A.tolist())               #Array to list

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [20]:
#the following array is given, transform it to the expected output using slice operator and print to the console
#[[ 0, 1, 2, 3],
#[ 4, 5, 6, 7],
#[ 8, 9, 10, 11]]

#expected output

#[[ 8 9 10 11]
#[ 4 5 6 7]
#[ 0 1 2 3]]

In [21]:
A=np.arange(12).reshape(3,4)
print(A[::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [22]:
print(np.flip(A,axis=0))

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [23]:
#the following array is given, transform it to the expected output
#[[1. 1. 1. 1.]
#[1. 1. 1. 1.]
#[1. 1. 1. 1.]
#[1. 1. 1. 1.]]

#expected output

#[[0. 0. 0. 0. 0. 0.]
#[0. 1. 1. 1. 1. 0.]
#[0. 1. 1. 1. 1. 0.]
#[0. 1. 1. 1. 1. 0.]
#[0. 1. 1. 1. 1. 0.]
#[0. 0. 0. 0. 0. 0.]]

#use pad() method

In [35]:
A=np.ones((4,4))
B=np.pad(A,pad_width=1,constant_values=0)
B

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [36]:
A=np.ones((4,4))
B=np.pad(A,pad_width=(1,2),constant_values=0)
B

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0., 0.],
       [0., 1., 1., 1., 1., 0., 0.],
       [0., 1., 1., 1., 1., 0., 0.],
       [0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [37]:
A=np.ones((4,4))
B=np.pad(A,pad_width=2,constant_values=0)
B

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
#the following array is given, transform it to the expected output.
#[[0 0 0 0 0 0]
#[0 0 0 0 0 0]
#[0 0 0 0 0 0]
#[0 0 0 0 0 0]
#[0 0 0 0 0 0]
#[0 0 0 0 0 0]]

#expected output

#[[10 0 10 0 10 0]
#[ 5 0 5 0 5 0]
#[10 0 10 0 10 0]
#[ 5 0 5 0 5 0]
#[10 0 10 0 10 0]
#[ 5 0 5 0 5 0]]

In [47]:
A=np.zeros((6,6))
A[::2,::2]=10  #second ::2 is for step
A[1::2,::2]=5
A

array([[10.,  0., 10.,  0., 10.,  0.],
       [ 5.,  0.,  5.,  0.,  5.,  0.],
       [10.,  0., 10.,  0., 10.,  0.],
       [ 5.,  0.,  5.,  0.,  5.,  0.],
       [10.,  0., 10.,  0., 10.,  0.],
       [ 5.,  0.,  5.,  0.,  5.,  0.]])

In [48]:
A=np.zeros((6,6))


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [50]:
#combine the following two arrays as one as shown and print to the console
#A=np.arange(12).reshape(3,4)
#B=np.array([[4,3,7,2],
#            [0,5,2,6]])

#expected output

#[[ 0 1 2 3]
#[ 4 5 6 7]
#[ 8 9 10 11]
#[ 4 3 7 2]
#[ 0 5 2 6]]

#use append() method

In [51]:
A=np.arange(12).reshape(3,4)
B=np.array([[4,3,7,2],
            [0,5,2,6]])
print(np.append(A,B,axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


In [52]:
#the following arrays are given, extract the same elements of the arrays as a list and print to the console
#A=np.arange(8).reshape(-1,4)
#B=np.array([[9,10,11,3],
#            [2,8,0,9]])

#use intersect1d() method


In [53]:
A=np.arange(8).reshape(-1,4)
B=np.array([[9,10,11,3],
            [2,8,0,9]])
print(np.intersect1d(A,B))  #it will get elements common to both arrays

[0 2 3]


In [54]:
#the following array is given, extract all the unique values and print to the console.
#use unique() method

In [55]:
np.random.seed(10)
A = np.random.randint(low=1, high=10, size=(3, 5))
print(A)

[[5 1 2 1 2]
 [9 1 9 7 5]
 [4 1 5 7 9]]


In [56]:
print(np.unique(A))

[1 2 4 5 7 9]


In [57]:
#the following array is given, return a list of indexes with maximum values for each row from this array and print to the console
#[[0.4 0.3 0.3]
#[0.1 0.1 0.8]
#[0.2 0.5 0.3]]

#use argmax() method

In [64]:
A=[[0.4,0.3,0.3],
[0.1,0.1,0.8],
[0.2,0.5,0.3]]
B=np.argmax(A,axis=1)
print(B)   #index of biggest element in each row

[0 2 1]
